import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/Header";
import Providers from "@/shared/provider/queryProvider";
import {Suspense} from "react";
import AppDialog from "@/components/app-dialog/AppDialog";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
      <Suspense>
        <Providers>
          <div className='flex-1 bg-white p-4'>
            <Header />
            {children}
          </div>
        </Providers>
        <AppDialog />
      </Suspense>
      </body>
    </html>
  );
}
